[package]
name = "tsq"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
emacs = "0.19.0"
libloading = "0.8.3"
tree-sitter = "0.22.5"
tree-sitter-loader = "0.22.5"


[lib]
crate-type = ["cdylib"]
